module CurateTumblr
  STATE_PUBLISHED = "published"
  STATE_DRAFT = "draft"
  STATE_QUEUE = "queue"
  STATE_PRIVATE = "private"

  CLIENT_STATUS_OK = 200
  CLIENT_STATUS_BAD_REQUEST = 400
  CLIENT_STATUS_NOT_AUTHORIZED = 401
  CLIENT_STATUS_NOT_FOUND = 404
  CLIENT_STATUS_RATE_LIMIT = 429
  COUNT_ALERT_IF_TOO_MUCH_BAD_REQUESTS = 5 

  DISPLAY_SLEEP_BEFORE = "("
  DISPLAY_SLEEP_AFTER = ")"
  DISPLAY_TUMBLR_POST = "+"
  DISPLAY_TUMBLR_REBLOG = ">"
  DISPLAY_TUMBLR_DELETE = "-"
  DISPLAY_TUMBLR_FOLLOW = ":"
  DISPLAY_TUMBLR_GETPOSTS = "?"

  SANDBOX_POST_ID = 1 # for testing without sending to tumblr
end